name: OS Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t os161-test-env .

    - name: Setup Delay
      run: sleep 10


    - name: Run Tests in Container
      run : |
        docker run -v ${{github.workspace}}:/os161/src os161-test-env /bin/bash -c "
                  source /os161/setup_env.sh 
                  test161 run syscalls/fileonlytest.t 
                "

    
