name: OS Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t os161-test-env .

    - name: Setup Delay
      run: sleep 10


    - name: Run Tests in Container
      run : |
        docker run -v ${{github.workspace}}:/os161/src os161-test-env /bin/bash -c "
                  cd /os161/src   
                  ls
                  ./configure --ostree=/os161/root 
                  sleep 4
                  cd /os161/src/kern/conf 
                  ./config ASST2 
                  sleep 4
                  cd /os161/src/kern/compile/ASST2 
                  sleep 4
                  bmake depend 
                  sleep 1 
                  bmake
                  sleep 1 
                  bmake install 
                  cd /os161/src
                  sleep 2
                  bmake depend 
                  sleep 2 
                  bmake
                  sleep 2
                  bmake install 
                  cd /os161/root
                  sleep 1
                  test161 run syscalls/fileonlytest.t
                "

    
