name: OS Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Buildtools
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ops-class/os161-toolchain
        sudo apt-get update
        sudo apt-get install -y os161-toolchain

    - name: Build OS
      run: |
        ./configure --ostree=~/root
        ./kern/conf/config ASST2
        cd kern/compile/ASST2
        bmake depend
        bmake
        bmake install
        cd ~
    
    - name: Build Programs
      run: |
        bmake depend
        bmake
        bmake install
        cd ~

    - name: Run Tests 
      run: |
        cd ~/root
        test161 run syscalls/fileonlytest.t


    
